In [85]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
df = pd.read_csv('datasets/cars.csv')

In [87]:
df.sample(5)

          brand  km_driven    fuel         owner  selling_price
1513     Toyota     110000  Diesel   First Owner         900000
8031  Chevrolet     195000  Diesel   First Owner         275000
7000     Maruti      70000  Petrol  Second Owner         130000
82          BMW      30000  Petrol  Second Owner        2500000
3036     Maruti      50000  Diesel   First Owner         740000

In [88]:
df.shape

(8128, 5)

In [89]:
df['brand'].nunique()

32

In [90]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [91]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [92]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [93]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [94]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [95]:
X = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [98]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [99]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=int)

In [100]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

In [101]:
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [102]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

In [103]:
X_train_new.shape

(6502, 7)

In [104]:
counts = df['brand'].value_counts()

In [105]:
df['brand'].nunique()
threshold = 100

In [106]:
repl = counts[counts <= threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [108]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), sparse=True, dtype=int).sample(20)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
129,0,0,0,0,0,0,1,0,0,0,0,0,0
405,0,0,0,0,0,0,1,0,0,0,0,0,0
3955,0,0,0,0,0,1,0,0,0,0,0,0,0
22,0,0,0,0,0,0,1,0,0,0,0,0,0
6065,0,0,0,0,0,0,0,0,0,0,0,0,1
2797,0,0,0,0,1,0,0,0,0,0,0,0,0
1968,0,0,0,0,0,0,0,0,0,0,1,0,0
5237,0,0,0,1,0,0,0,0,0,0,0,0,0
4708,0,0,0,0,0,0,0,0,0,1,0,0,0
4681,0,0,0,0,0,1,0,0,0,0,0,0,0
3948,0,0,0,0,0,0,1,0,0,0,0,0,0
1705,0,0,0,0,1,0,0,0,0,0,0,0,0
7410,0,0,0,0,0,0,1,0,0,0,0,0,0
4043,0,0,0,0,0,0,0,0,0,1,0,0,0
456,0,0,0,1,0,0,0,0,0,0,0,0,0
2981,0,0,0,0,0,0,0,0,0,0,1,0,0
3613,0,0,0,0,0,0,1,0,0,0,0,0,0
5337,0,0,0,0,0,1,0,0,0,0,0,0,0
7279,0,0,0,0,0,0,0,0,0,0,0,1,0
1102,0,0,0,0,0,0,1,0,0,0,0,0,0