In [259]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [260]:
df = pd.read_csv('datasets/covid_toy.csv')

In [261]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [262]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [263]:
df.cough.value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [264]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [265]:
X_train

    age  gender  fever   cough       city
42   27    Male  100.0    Mild      Delhi
60   24  Female  102.0  Strong  Bangalore
77    8  Female  101.0    Mild    Kolkata
36   38  Female  101.0    Mild  Bangalore
67   65    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
37   55    Male  100.0    Mild    Kolkata
2    42    Male  101.0    Mild      Delhi
75    5    Male  102.0    Mild    Kolkata
20   12    Male   98.0  Strong  Bangalore
94   79    Male    NaN  Strong    Kolkata

[80 rows x 5 columns]

In [266]:
si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.transform(X_test[['fever']])

In [267]:
X_train_fever.shape

(80, 1)

In [268]:
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])

In [269]:
X_train_cough.shape

(80, 1)

In [270]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])
X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

In [271]:
X_train_gender_city.shape

(80, 4)

In [272]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

In [273]:
X_test_age.shape

(20, 1)

In [274]:
X_train_transform = np.concatenate((X_train_age, X_train_gender_city, X_train_cough, X_train_fever), axis=1)
X_test_transform = np.concatenate((X_test_age, X_test_gender_city, X_test_cough, X_test_fever), axis=1)

In [275]:
X_train_transform.shape

(80, 7)

In [276]:
from sklearn.compose import ColumnTransformer

In [277]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
], remainder='passthrough')

In [279]:
transformer.fit_transform(X_train).shape

(80, 7)

In [280]:
transformer.transform(X_test)

array([[102.       ,   1.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  20.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  14.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  64.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [ 98.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  40.       ],
       [100.8630137,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  25.       ],
       [104.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  56.       ],
       [ 99.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  65.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  10.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  70.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  10.       ],
       [100.8630137,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  16.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  11.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  11.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  50.       ],
       [100.8630137,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  34.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ]])