In [2386]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2387]:
df = pd.read_csv('datasets/train.csv')[['Age','Pclass','Fare','Survived']]

In [2388]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [2389]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [2390]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [2391]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [2392]:
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [2393]:
knn = KNNImputer(n_neighbors=3, weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.fit_transform(X_test)

In [2394]:
lr =LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.7094972067039106

In [2395]:
X_train.head(3)

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000

In [2396]:
X_test.tail()

      Age  Pclass     Fare
89   24.0       3   8.0500
80   22.0       3   9.0000
846   NaN       3  69.5500
870  26.0       3   7.8958
251  29.0       3  10.4625

In [2398]:
mask_train = X_train['Age'].isnull()
mask_test = X_test['Age'].isnull()

X_train.loc[mask_train,'Age']=X_train['Age'].dropna().sample(mask_train.sum()).values

X_test.loc[mask_test, 'Age'] = X_train['Age'].dropna().sample(mask_test.sum()).values

In [2399]:
X_train.isnull().sum()

Age       0
Pclass    0
Fare      0
dtype: int64

In [2400]:
lr = LogisticRegression()

lr.fit(X_train,y_train)

y_pred2 = lr.predict(X_test)

accuracy_score(y_test,y_pred2)

0.664804469273743

In [ ]:
si = SimpleImputer(add_indicator=True)

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [ ]:
X_train_trf2

array([[ 40.        ,   1.        ,  27.7208    ,   0.        ],
       [  4.        ,   3.        ,  16.7       ,   0.        ],
       [ 47.        ,   3.        ,   9.        ,   0.        ],
       ...,
       [ 71.        ,   1.        ,  49.5042    ,   0.        ],
       [ 29.78590426,   1.        , 221.7792    ,   1.        ],
       [ 29.78590426,   1.        ,  25.925     ,   1.        ]],
      shape=(712, 4))

In [ ]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6983240223463687